/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsApply } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsApply';
import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsComposite } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsComposite';
import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsCustom } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsCustom';
import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsExec } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsExec';
import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsVscodeLaunch } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsVscodeLaunch';
import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsVscodeTask } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsVscodeTask';

export class V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommands {
    'apply'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsApply;
    /**
    * Type of workspace command
    */
    'commandType'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommands.CommandTypeEnum;
    'composite'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsComposite;
    'custom'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsCustom;
    'exec'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsExec;
    'vscodeLaunch'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsVscodeLaunch;
    'vscodeTask'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsVscodeTask;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apply",
            "baseName": "apply",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsApply"
        },
        {
            "name": "commandType",
            "baseName": "commandType",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommands.CommandTypeEnum"
        },
        {
            "name": "composite",
            "baseName": "composite",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsComposite"
        },
        {
            "name": "custom",
            "baseName": "custom",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsCustom"
        },
        {
            "name": "exec",
            "baseName": "exec",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsExec"
        },
        {
            "name": "vscodeLaunch",
            "baseName": "vscodeLaunch",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsVscodeLaunch"
        },
        {
            "name": "vscodeTask",
            "baseName": "vscodeTask",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommandsItemsVscodeTask"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommands.attributeTypeMap;
    }
}

export namespace V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginCommands {
    export enum CommandTypeEnum {
        Exec = <any> 'Exec',
        Apply = <any> 'Apply',
        VscodeTask = <any> 'VscodeTask',
        VscodeLaunch = <any> 'VscodeLaunch',
        Composite = <any> 'Composite',
        Custom = <any> 'Custom'
    }
}
