/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsContainer } from './v1alpha1DevWorkspaceSpecTemplateParentComponentsItemsContainer';
import { V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsCustom } from './v1alpha1DevWorkspaceSpecTemplateParentComponentsItemsCustom';
import { V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsKubernetes } from './v1alpha1DevWorkspaceSpecTemplateParentComponentsItemsKubernetes';
import { V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsOpenshift } from './v1alpha1DevWorkspaceSpecTemplateParentComponentsItemsOpenshift';
import { V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPlugin } from './v1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPlugin';
import { V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsVolume } from './v1alpha1DevWorkspaceSpecTemplateParentComponentsItemsVolume';

export class V1alpha1DevWorkspaceSpecTemplateParentComponents {
    /**
    * Type of component
    */
    'componentType'?: V1alpha1DevWorkspaceSpecTemplateParentComponents.ComponentTypeEnum;
    'container'?: V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsContainer;
    'custom'?: V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsCustom;
    'kubernetes'?: V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsKubernetes;
    'openshift'?: V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsOpenshift;
    'plugin'?: V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPlugin;
    'volume'?: V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsVolume;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "componentType",
            "baseName": "componentType",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentComponents.ComponentTypeEnum"
        },
        {
            "name": "container",
            "baseName": "container",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsContainer"
        },
        {
            "name": "custom",
            "baseName": "custom",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsCustom"
        },
        {
            "name": "kubernetes",
            "baseName": "kubernetes",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsKubernetes"
        },
        {
            "name": "openshift",
            "baseName": "openshift",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsOpenshift"
        },
        {
            "name": "plugin",
            "baseName": "plugin",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPlugin"
        },
        {
            "name": "volume",
            "baseName": "volume",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsVolume"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DevWorkspaceSpecTemplateParentComponents.attributeTypeMap;
    }
}

export namespace V1alpha1DevWorkspaceSpecTemplateParentComponents {
    export enum ComponentTypeEnum {
        Container = <any> 'Container',
        Kubernetes = <any> 'Kubernetes',
        Openshift = <any> 'Openshift',
        Volume = <any> 'Volume',
        Plugin = <any> 'Plugin',
        Custom = <any> 'Custom'
    }
}
