/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1DevWorkspaceSpecTemplateCommandsItemsApply } from './v1alpha1DevWorkspaceSpecTemplateCommandsItemsApply';
import { V1alpha1DevWorkspaceSpecTemplateCommandsItemsComposite } from './v1alpha1DevWorkspaceSpecTemplateCommandsItemsComposite';
import { V1alpha1DevWorkspaceSpecTemplateCommandsItemsCustom } from './v1alpha1DevWorkspaceSpecTemplateCommandsItemsCustom';
import { V1alpha1DevWorkspaceSpecTemplateCommandsItemsExec } from './v1alpha1DevWorkspaceSpecTemplateCommandsItemsExec';
import { V1alpha1DevWorkspaceSpecTemplateCommandsItemsVscodeLaunch } from './v1alpha1DevWorkspaceSpecTemplateCommandsItemsVscodeLaunch';
import { V1alpha1DevWorkspaceSpecTemplateCommandsItemsVscodeTask } from './v1alpha1DevWorkspaceSpecTemplateCommandsItemsVscodeTask';

export class V1alpha1DevWorkspaceSpecTemplateCommands {
    'apply'?: V1alpha1DevWorkspaceSpecTemplateCommandsItemsApply;
    /**
    * Type of workspace command
    */
    'commandType'?: V1alpha1DevWorkspaceSpecTemplateCommands.CommandTypeEnum;
    'composite'?: V1alpha1DevWorkspaceSpecTemplateCommandsItemsComposite;
    'custom'?: V1alpha1DevWorkspaceSpecTemplateCommandsItemsCustom;
    'exec'?: V1alpha1DevWorkspaceSpecTemplateCommandsItemsExec;
    'vscodeLaunch'?: V1alpha1DevWorkspaceSpecTemplateCommandsItemsVscodeLaunch;
    'vscodeTask'?: V1alpha1DevWorkspaceSpecTemplateCommandsItemsVscodeTask;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apply",
            "baseName": "apply",
            "type": "V1alpha1DevWorkspaceSpecTemplateCommandsItemsApply"
        },
        {
            "name": "commandType",
            "baseName": "commandType",
            "type": "V1alpha1DevWorkspaceSpecTemplateCommands.CommandTypeEnum"
        },
        {
            "name": "composite",
            "baseName": "composite",
            "type": "V1alpha1DevWorkspaceSpecTemplateCommandsItemsComposite"
        },
        {
            "name": "custom",
            "baseName": "custom",
            "type": "V1alpha1DevWorkspaceSpecTemplateCommandsItemsCustom"
        },
        {
            "name": "exec",
            "baseName": "exec",
            "type": "V1alpha1DevWorkspaceSpecTemplateCommandsItemsExec"
        },
        {
            "name": "vscodeLaunch",
            "baseName": "vscodeLaunch",
            "type": "V1alpha1DevWorkspaceSpecTemplateCommandsItemsVscodeLaunch"
        },
        {
            "name": "vscodeTask",
            "baseName": "vscodeTask",
            "type": "V1alpha1DevWorkspaceSpecTemplateCommandsItemsVscodeTask"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DevWorkspaceSpecTemplateCommands.attributeTypeMap;
    }
}

export namespace V1alpha1DevWorkspaceSpecTemplateCommands {
    export enum CommandTypeEnum {
        Exec = <any> 'Exec',
        Apply = <any> 'Apply',
        VscodeTask = <any> 'VscodeTask',
        VscodeLaunch = <any> 'VscodeLaunch',
        Composite = <any> 'Composite',
        Custom = <any> 'Custom'
    }
}
