/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsContainer } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsContainer';
import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsCustom } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsCustom';
import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsKubernetes } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsKubernetes';
import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsOpenshift } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsOpenshift';
import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsPlugin } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsPlugin';
import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsVolume } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsVolume';

export class V1alpha1DevWorkspaceSpecTemplateComponents {
    /**
    * Type of component
    */
    'componentType'?: V1alpha1DevWorkspaceSpecTemplateComponents.ComponentTypeEnum;
    'container'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsContainer;
    'custom'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsCustom;
    'kubernetes'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsKubernetes;
    'openshift'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsOpenshift;
    'plugin'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsPlugin;
    'volume'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsVolume;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "componentType",
            "baseName": "componentType",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponents.ComponentTypeEnum"
        },
        {
            "name": "container",
            "baseName": "container",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsContainer"
        },
        {
            "name": "custom",
            "baseName": "custom",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsCustom"
        },
        {
            "name": "kubernetes",
            "baseName": "kubernetes",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsKubernetes"
        },
        {
            "name": "openshift",
            "baseName": "openshift",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsOpenshift"
        },
        {
            "name": "plugin",
            "baseName": "plugin",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsPlugin"
        },
        {
            "name": "volume",
            "baseName": "volume",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsVolume"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DevWorkspaceSpecTemplateComponents.attributeTypeMap;
    }
}

export namespace V1alpha1DevWorkspaceSpecTemplateComponents {
    export enum ComponentTypeEnum {
        Container = <any> 'Container',
        Kubernetes = <any> 'Kubernetes',
        Openshift = <any> 'Openshift',
        Volume = <any> 'Volume',
        Plugin = <any> 'Plugin',
        Custom = <any> 'Custom'
    }
}
