/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1DevWorkspaceSpecTemplateProjectsItemsCustom } from './v1alpha1DevWorkspaceSpecTemplateProjectsItemsCustom';
import { V1alpha1DevWorkspaceSpecTemplateProjectsItemsGit } from './v1alpha1DevWorkspaceSpecTemplateProjectsItemsGit';
import { V1alpha1DevWorkspaceSpecTemplateProjectsItemsGithub } from './v1alpha1DevWorkspaceSpecTemplateProjectsItemsGithub';
import { V1alpha1DevWorkspaceSpecTemplateProjectsItemsZip } from './v1alpha1DevWorkspaceSpecTemplateProjectsItemsZip';

export class V1alpha1DevWorkspaceSpecTemplateProjects {
    /**
    * Path relative to the root of the projects to which this project should be cloned into. This is a unix-style relative path (i.e. uses forward slashes). The path is invalid if it is absolute or tries to escape the project root through the usage of \'..\'. If not specified, defaults to the project name.
    */
    'clonePath'?: string;
    'custom'?: V1alpha1DevWorkspaceSpecTemplateProjectsItemsCustom;
    'git'?: V1alpha1DevWorkspaceSpecTemplateProjectsItemsGit;
    'github'?: V1alpha1DevWorkspaceSpecTemplateProjectsItemsGithub;
    /**
    * Project name
    */
    'name': string;
    /**
    * Type of project source
    */
    'sourceType'?: V1alpha1DevWorkspaceSpecTemplateProjects.SourceTypeEnum;
    'zip'?: V1alpha1DevWorkspaceSpecTemplateProjectsItemsZip;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "clonePath",
            "baseName": "clonePath",
            "type": "string"
        },
        {
            "name": "custom",
            "baseName": "custom",
            "type": "V1alpha1DevWorkspaceSpecTemplateProjectsItemsCustom"
        },
        {
            "name": "git",
            "baseName": "git",
            "type": "V1alpha1DevWorkspaceSpecTemplateProjectsItemsGit"
        },
        {
            "name": "github",
            "baseName": "github",
            "type": "V1alpha1DevWorkspaceSpecTemplateProjectsItemsGithub"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "sourceType",
            "baseName": "sourceType",
            "type": "V1alpha1DevWorkspaceSpecTemplateProjects.SourceTypeEnum"
        },
        {
            "name": "zip",
            "baseName": "zip",
            "type": "V1alpha1DevWorkspaceSpecTemplateProjectsItemsZip"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DevWorkspaceSpecTemplateProjects.attributeTypeMap;
    }
}

export namespace V1alpha1DevWorkspaceSpecTemplateProjects {
    export enum SourceTypeEnum {
        Git = <any> 'Git',
        Github = <any> 'Github',
        Zip = <any> 'Zip',
        Custom = <any> 'Custom'
    }
}
