/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsKubernetesEndpoints } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsKubernetesEndpoints';

/**
* Allows importing into the workspace the Kubernetes resources defined in a given manifest. For example this allows reusing the Kubernetes definitions used to deploy some runtime components in production.
*/
export class V1alpha1DevWorkspaceSpecTemplateComponentsItemsKubernetes {
    'endpoints'?: Array<V1alpha1DevWorkspaceSpecTemplateComponentsItemsKubernetesEndpoints>;
    /**
    * Inlined manifest
    */
    'inlined'?: string;
    /**
    * Type of Kubernetes-like location
    */
    'locationType'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsKubernetes.LocationTypeEnum;
    /**
    * Mandatory name that allows referencing the component in commands, or inside a parent
    */
    'name': string;
    /**
    * Location in a file fetched from a uri.
    */
    'uri'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "endpoints",
            "baseName": "endpoints",
            "type": "Array<V1alpha1DevWorkspaceSpecTemplateComponentsItemsKubernetesEndpoints>"
        },
        {
            "name": "inlined",
            "baseName": "inlined",
            "type": "string"
        },
        {
            "name": "locationType",
            "baseName": "locationType",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsKubernetes.LocationTypeEnum"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DevWorkspaceSpecTemplateComponentsItemsKubernetes.attributeTypeMap;
    }
}

export namespace V1alpha1DevWorkspaceSpecTemplateComponentsItemsKubernetes {
    export enum LocationTypeEnum {
        Uri = <any> 'Uri',
        Inlined = <any> 'Inlined'
    }
}
