/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsApply } from './v1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsApply';
import { V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsComposite } from './v1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsComposite';
import { V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsCustom } from './v1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsCustom';
import { V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsExec } from './v1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsExec';
import { V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsVscodeLaunch } from './v1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsVscodeLaunch';
import { V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsVscodeTask } from './v1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsVscodeTask';

export class V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommands {
    'apply'?: V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsApply;
    /**
    * Type of workspace command
    */
    'commandType'?: V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommands.CommandTypeEnum;
    'composite'?: V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsComposite;
    'custom'?: V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsCustom;
    'exec'?: V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsExec;
    'vscodeLaunch'?: V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsVscodeLaunch;
    'vscodeTask'?: V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsVscodeTask;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apply",
            "baseName": "apply",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsApply"
        },
        {
            "name": "commandType",
            "baseName": "commandType",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommands.CommandTypeEnum"
        },
        {
            "name": "composite",
            "baseName": "composite",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsComposite"
        },
        {
            "name": "custom",
            "baseName": "custom",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsCustom"
        },
        {
            "name": "exec",
            "baseName": "exec",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsExec"
        },
        {
            "name": "vscodeLaunch",
            "baseName": "vscodeLaunch",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsVscodeLaunch"
        },
        {
            "name": "vscodeTask",
            "baseName": "vscodeTask",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommandsItemsVscodeTask"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommands.attributeTypeMap;
    }
}

export namespace V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsPluginCommands {
    export enum CommandTypeEnum {
        Exec = <any> 'Exec',
        Apply = <any> 'Apply',
        VscodeTask = <any> 'VscodeTask',
        VscodeLaunch = <any> 'VscodeLaunch',
        Composite = <any> 'Composite',
        Custom = <any> 'Custom'
    }
}
