/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsCustomGroup } from './v1alpha1DevWorkspaceSpecTemplateParentCommandsItemsCustomGroup';

/**
* Custom command whose logic is implementation-dependant and should be provided by the user possibly through some dedicated plugin
*/
export class V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsCustom {
    /**
    * Optional map of free-form additional command attributes
    */
    'attributes'?: { [key: string]: string; };
    /**
    * Class of command that the associated implementation component should use to process this command with the appropriate logic
    */
    'commandClass': string;
    /**
    * Additional free-form configuration for this custom command that the implementation component will know how to use
    */
    'embeddedResource': object;
    'group'?: V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsCustomGroup;
    /**
    * Mandatory identifier that allows referencing this command in composite commands, from a parent, or in events.
    */
    'id': string;
    /**
    * Optional label that provides a label for this command to be used in Editor UI menus for example
    */
    'label'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "commandClass",
            "baseName": "commandClass",
            "type": "string"
        },
        {
            "name": "embeddedResource",
            "baseName": "embeddedResource",
            "type": "object"
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsCustomGroup"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsCustom.attributeTypeMap;
    }
}

