/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Project\'s Zip source
*/
export class V1alpha1DevWorkspaceSpecTemplateStarterProjectsItemsZip {
    /**
    * Zip project\'s source location address. Should be file path of the archive, e.g. file://$FILE_PATH
    */
    'location'?: string;
    /**
    * Part of project to populate in the working directory.
    */
    'sparseCheckoutDir'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "location",
            "baseName": "location",
            "type": "string"
        },
        {
            "name": "sparseCheckoutDir",
            "baseName": "sparseCheckoutDir",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DevWorkspaceSpecTemplateStarterProjectsItemsZip.attributeTypeMap;
    }
}

