/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1DevWorkspaceSpecTemplate } from './v1alpha1DevWorkspaceSpecTemplate';

/**
* DevWorkspaceSpec defines the desired state of DevWorkspace
*/
export class V1alpha1DevWorkspaceSpec {
    'routingClass'?: string;
    'started': boolean;
    'template'?: V1alpha1DevWorkspaceSpecTemplate;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "routingClass",
            "baseName": "routingClass",
            "type": "string"
        },
        {
            "name": "started",
            "baseName": "started",
            "type": "boolean"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "V1alpha1DevWorkspaceSpecTemplate"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DevWorkspaceSpec.attributeTypeMap;
    }
}

