/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Defines from what the project should be checked out. Required if there are more than one remote configured
*/
export class V1alpha1DevWorkspaceSpecTemplateParentStarterProjectsItemsGithubCheckoutFrom {
    /**
    * The remote name should be used as init. Required if there are more than one remote configured
    */
    'remote'?: string;
    /**
    * The revision to checkout from. Should be branch name, tag or commit id. Default branch is used if missing or specified revision is not found.
    */
    'revision'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "remote",
            "baseName": "remote",
            "type": "string"
        },
        {
            "name": "revision",
            "baseName": "revision",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DevWorkspaceSpecTemplateParentStarterProjectsItemsGithubCheckoutFrom.attributeTypeMap;
    }
}

