/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Allows specifying the definition of a volume shared by several other components
*/
export class V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsVolume {
    /**
    * Ephemeral volumes are not stored persistently across restarts. Defaults to false
    */
    'ephemeral'?: boolean;
    /**
    * Mandatory name that allows referencing the Volume component in Container volume mounts or inside a parent
    */
    'name': string;
    /**
    * Size of the volume
    */
    'size'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ephemeral",
            "baseName": "ephemeral",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DevWorkspaceSpecTemplateParentComponentsItemsVolume.attributeTypeMap;
    }
}

