/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsApply } from './v1alpha1DevWorkspaceSpecTemplateParentCommandsItemsApply';
import { V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsComposite } from './v1alpha1DevWorkspaceSpecTemplateParentCommandsItemsComposite';
import { V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsCustom } from './v1alpha1DevWorkspaceSpecTemplateParentCommandsItemsCustom';
import { V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsExec } from './v1alpha1DevWorkspaceSpecTemplateParentCommandsItemsExec';
import { V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsVscodeLaunch } from './v1alpha1DevWorkspaceSpecTemplateParentCommandsItemsVscodeLaunch';
import { V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsVscodeTask } from './v1alpha1DevWorkspaceSpecTemplateParentCommandsItemsVscodeTask';

export class V1alpha1DevWorkspaceSpecTemplateParentCommands {
    'apply'?: V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsApply;
    /**
    * Type of workspace command
    */
    'commandType'?: V1alpha1DevWorkspaceSpecTemplateParentCommands.CommandTypeEnum;
    'composite'?: V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsComposite;
    'custom'?: V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsCustom;
    'exec'?: V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsExec;
    'vscodeLaunch'?: V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsVscodeLaunch;
    'vscodeTask'?: V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsVscodeTask;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apply",
            "baseName": "apply",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsApply"
        },
        {
            "name": "commandType",
            "baseName": "commandType",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentCommands.CommandTypeEnum"
        },
        {
            "name": "composite",
            "baseName": "composite",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsComposite"
        },
        {
            "name": "custom",
            "baseName": "custom",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsCustom"
        },
        {
            "name": "exec",
            "baseName": "exec",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsExec"
        },
        {
            "name": "vscodeLaunch",
            "baseName": "vscodeLaunch",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsVscodeLaunch"
        },
        {
            "name": "vscodeTask",
            "baseName": "vscodeTask",
            "type": "V1alpha1DevWorkspaceSpecTemplateParentCommandsItemsVscodeTask"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DevWorkspaceSpecTemplateParentCommands.attributeTypeMap;
    }
}

export namespace V1alpha1DevWorkspaceSpecTemplateParentCommands {
    export enum CommandTypeEnum {
        Exec = <any> 'Exec',
        Apply = <any> 'Apply',
        VscodeTask = <any> 'VscodeTask',
        VscodeLaunch = <any> 'VscodeLaunch',
        Composite = <any> 'Composite',
        Custom = <any> 'Custom'
    }
}
