/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1DevWorkspaceSpecTemplateStarterProjectsItemsGitCheckoutFrom } from './v1alpha1DevWorkspaceSpecTemplateStarterProjectsItemsGitCheckoutFrom';

/**
* Project\'s Git source
*/
export class V1alpha1DevWorkspaceSpecTemplateStarterProjectsItemsGit {
    'checkoutFrom'?: V1alpha1DevWorkspaceSpecTemplateStarterProjectsItemsGitCheckoutFrom;
    /**
    * The remotes map which should be initialized in the git project. Must have at least one remote configured
    */
    'remotes'?: { [key: string]: string; };
    /**
    * Part of project to populate in the working directory.
    */
    'sparseCheckoutDir'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "checkoutFrom",
            "baseName": "checkoutFrom",
            "type": "V1alpha1DevWorkspaceSpecTemplateStarterProjectsItemsGitCheckoutFrom"
        },
        {
            "name": "remotes",
            "baseName": "remotes",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "sparseCheckoutDir",
            "baseName": "sparseCheckoutDir",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DevWorkspaceSpecTemplateStarterProjectsItemsGit.attributeTypeMap;
    }
}

