/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: master
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsContainer } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsContainer';
import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsKubernetes } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsKubernetes';
import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsOpenshift } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsOpenshift';
import { V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsVolume } from './v1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsVolume';

export class V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponents {
    /**
    * Type of component override for a plugin
    */
    'componentType'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponents.ComponentTypeEnum;
    'container'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsContainer;
    'kubernetes'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsKubernetes;
    'openshift'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsOpenshift;
    'volume'?: V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsVolume;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "componentType",
            "baseName": "componentType",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponents.ComponentTypeEnum"
        },
        {
            "name": "container",
            "baseName": "container",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsContainer"
        },
        {
            "name": "kubernetes",
            "baseName": "kubernetes",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsKubernetes"
        },
        {
            "name": "openshift",
            "baseName": "openshift",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsOpenshift"
        },
        {
            "name": "volume",
            "baseName": "volume",
            "type": "V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponentsItemsVolume"
        }    ];

    static getAttributeTypeMap() {
        return V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponents.attributeTypeMap;
    }
}

export namespace V1alpha1DevWorkspaceSpecTemplateComponentsItemsPluginComponents {
    export enum ComponentTypeEnum {
        Container = <any> 'Container',
        Kubernetes = <any> 'Kubernetes',
        Openshift = <any> 'Openshift',
        Volume = <any> 'Volume'
    }
}
